// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCharacter() {
  return window['go']['main']['CharacterApi']['GetCharacter']();
}

export function SetName(arg1) {
  return window['go']['main']['CharacterApi']['SetName'](arg1);
}
